+ tornado==6.4.2

 + twilio==9.5.0

 + typing-extensions==4.12.2

 + typing-inspection==0.4.0

 + tzdata==2025.1

 + tzlocal==5.3.1

 + uritemplate==4.2.0

 + urllib3==2.3.0

 + watchdog==6.0.0

 + yarl==1.18.3[2025-07-20 10:07:49.741838] 

[10:07:50] üêç Python dependencies were installed from /mount/src/lang-huu-nghi-management/uv.lock using uv-sync.

[10:07:50] üì¶ WARN: More than one requirements file detected in the repository. Available options: uv-sync /mount/src/lang-huu-nghi-management/uv.lock, poetry /mount/src/lang-huu-nghi-management/pyproject.toml. Used: uv-sync with /mount/src/lang-huu-nghi-management/uv.lock

Check if streamlit is installed

Streamlit is already installed

[10:07:52] üì¶ Processed dependencies!




[10:07:56] ‚ùóÔ∏è The service has encountered an error while checking the health of the Streamlit app: Get "http://localhost:8501/healthz": dial tcp 127.0.0.1:8501: connect: connection refused

[10:09:21] üêô Pulling code changes from Github...

2025-07-20 10:09:22.162 An update to the [server] config option section was detected. To have these changes be reflected, please restart streamlit.

[10:09:22] üì¶ Processing dependencies...

[10:09:22] üì¶ Apt dependencies were installed from /mount/src/lang-huu-nghi-management/packages.txt using apt-get.

[10:09:22] üì¶ Processed dependencies!

  Stopping...




[10:09:27] üîÑ Updated app!

2025-07-20 10:09:40.087 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec

    exec(code, module.__dict__)

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/lang-huu-nghi-management/streamlit_app.py", line 4, in <module>

    from main import main

ModuleNotFoundError: No module named 'main'

2025-07-20 10:09:42.113 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec

    exec(code, module.__dict__)

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/lang-huu-nghi-management/streamlit_app.py", line 4, in <module>

    from main import main

ModuleNotFoundError: No module named 'main'

2025-07-20 10:09:53.127 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec

    exec(code, module.__dict__)

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/lang-huu-nghi-management/streamlit_app.py", line 4, in <module>

    from main import main

ModuleNotFoundError: No module named 'main'

2025-07-20 10:09:54.978 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 593, in code_to_exec

    exec(code, module.__dict__)

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/lang-huu-nghi-management/streamlit_app.py", line 4, in <module>

    from main import main

ModuleNotFoundError: No module named 'main'